name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build
      run: go build -v -o myapp ./...

    - name: Test
      run: go test -v ./...

    - name: Create Release
      if: github.event_name == 'push' && github.ref == 'refs/heads/master'
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v1.0.0
        release_name: Release v1.0.0
        draft: false
        prerelease: false
        body: |
          ## Features
          - Feature 1
          - Feature 2
        commitish: master
        asset_path: ./myapp
        asset_name: myapp-linux-amd64
        asset_content_type: application/octet-stream
