name: Build and Release

on:
  workflow_dispatch:  # 手动触发
  push:
    tags:
      - 'v*'  # 仅在以 'v' 开头的标签推送时触发

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.20'  # 指定 Go 版本

    - name: Install Make
      run: sudo apt-get install -y make  # 安装 make 工具

    - name: Build with Makefile
      run: make build_all  # 使用 Makefile 中的 build_all 目标

    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.ref_name }}  # 使用标签名称
        files: |
          bin/linux-amd64/*
          bin/linux-arm64/*
          bin/darwin-amd64/*
          bin/darwin-arm64/*
          bin/windows-amd64/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
